version: "3.8"

services:

  # Redis Service 
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/root/redis
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_PORT=6379
      - REDIS_DATABASES=1

  # Dash Example App
  dash_app:
    build:
      context: ../
      dockerfile: ./docker/dash_app.Dockerfile
    image: redsofa/dash_app:latest
    container_name:
      dash_app
    networks:
      - default
    ports:
      - "8080:8080"
    volumes:
      - ../src/python:/src/python
    environment:
      - TZ=America/Moncton
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  # MQTT Client Example
  mqtt_client:
    build:
      context: ../
      dockerfile: ./docker/mqtt_client.Dockerfile
    image: redsofa/mqtt_client:latest
    container_name: mqtt_client
    networks:
      - default
    volumes:
      - ../src/python:/src/python
    environment:
      - TZ=America/Moncton
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    networks:
      - default
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./mqtt/config:/mosquitto/config:rw
      - ./mqtt/data:/mosquitto/data:rw
      - ./mqtt/log:/mosquitto/log:rw

networks:
  default:
    name: beacon-test-network
